### PR TITLE
txsort: BIPLI01 has been accepted as BIP69, update README as such

### PR DESCRIPTION
**Pull request by Roasbeef**
BIPLI01 has been accepted as BIP0069, so update the README, comments,
tests, and testdata files as such.

---
This change is [Reviewable](https://reviewable.io/reviews/btcsuite/btcutil/70)

### CODE REVIEW

**Comment by davecgh** [comment]
Thanks for the PR.  Would you please make the commit message match the [Model Git Commit Message](https://github.com/btcsuite/btcd/blob/master/docs/code_contribution_guidelines.md#ModelGitCommitMessages) format as documented in the code contribution guidelines?

In particular, the summary is too long.

The following would probably work:

```
txsort: Update README for BIP0069 acceptance.

BIPLI01 has been accepted as BIP0069, so update the README as such.
```

**Comment by davecgh** [comment]
Also, if you would rebase it to the latest master, it will resolve the TravisCI build failures as I just merged a couple of PRs to update it to the most recent Go versions.

**Comment by davecgh** [comment]
Oh, while here, it might make sense to update the comments on the functions in `txsort.go` too.  I just noticed they say BIPLI01.

**Comment by davecgh** [comment]
There is also another reference in `doc.go`.

**Comment by Roasbeef** [comment]
Just pushed an update. I've fixed the comments in `txsort.go`, `txsort_test.go`, and `doc.go`. Additionally, I've renamed the test files used for the table driven tests in the `testdata` directory.

**Comment by davecgh** [comment]
Thanks.  Looks good now.

OK

**Pull request merged**
