### PR TITLE
hdkeychain: add CloneWithVersion to set custom HD version bytes

### PR DESCRIPTION
**Pull request by onyb**
|GH| #179 | https://github.com/btcsuite/btcd/pull/1617 |
-|-|-

This adds a new method to the `ExtendedKey` type that allows cloning the extended key with custom HD version bytes. It does not mutate the original extended key on which the method is called.

Added some tests to demonstrate the utility of this method, i.e., conversion between standard and [**`SLIP-0132`**](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) extended keys.

### CODE REVIEW

**Comment by mflaxman** [comment]
What's the status of getting this merged? It's needed to take advantage of the functionality added in https://github.com/btcsuite/btcd/pull/1617.

**Review by mflaxman — APPROVED** [review]

**Comment by onyb** [comment]
@mflaxman Thanks for the reminder. Kinda forgot to follow up on this with the other reviewers. Should be quick, since the changes are quite straightforward.

**Comment by mflaxman** [comment]
FYI: I open-sourced my hackey code (that doesn't use these pending PRs) if you want to see what a use-case looks like.

https://github.com/mflaxman/human-rng-golang

**Review by jcvernaleo — APPROVED** [review]
OK

**Review by jakesyl — APPROVED** [review]

**Pull request merged**
