### PR TITLE
build: Add unconvert linter to goclean.sh

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by jcvernaleo** [comment]
#83 already does this (and passes travis) so there is no reason for this PR.

**Comment by dajohi** [comment]
#83 is missing a unconvert and gosimple.

**Comment by jcvernaleo** [comment]
Those should be added as a seperate PR and not part of the first one so I still do not think this one should go in.  That is the way we did it for the other repo

**Comment by davecgh** [comment]
I will be merging #83.  Would you please split the addition of `unconvert` and `gosimple` into separate PRs on top of #83 much like it was done in btcd?

**Comment by davecgh** [comment]
Alright #83 has been merged.  Please rebase this one and redact it such that it only contains the `unconvert` changes and update the commit message and PR title accordingly.  Then a separate PR for `gosimple`, so it's consistent with the other repos.

**Comment by dajohi** [comment]
Updated.

**Pull request merged**
